# Generated by Django 3.1.2 on 2020-11-23 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CovidScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contact_with_covid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(help_text='Enter a title for this event', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this event across whole system', primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.account')),
                ('custom_covid_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreen')),
            ],
        ),
        migrations.CreateModel(
            name='CovidScreenInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescreen.account')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreen')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.event')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='events',
            field=models.ManyToManyField(to='prescreen.Event'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
