# Generated by Django 3.1.2 on 2020-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0002_auto_20201123_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidScreenQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(blank=True, max_length=200)),
                ('question_2', models.CharField(blank=True, max_length=200)),
                ('question_3', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='covidscreeninstance',
            name='details',
        ),
        migrations.AddField(
            model_name='covidscreeninstance',
            name='contact_with_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidscreeninstance',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=98.6, max_digits=5),
        ),
        migrations.DeleteModel(
            name='CovidScreen',
        ),
    ]
