# Generated by Django 3.1.2 on 2020-11-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0003_auto_20201123_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovidScreenQuestions',
            new_name='CovidScreenQuestionSet',
        ),
    ]
