# Generated by Django 3.1.2 on 2020-11-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0004_auto_20201123_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidscreeninstance',
            name='contact_with_covid',
        ),
        migrations.RemoveField(
            model_name='covidscreeninstance',
            name='temperature',
        ),
        migrations.CreateModel(
            name='CovidScreenDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=98.6, max_digits=5)),
                ('contact_with_covid', models.BooleanField(default=False)),
                ('custom_responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreenquestionset')),
            ],
        ),
        migrations.AddField(
            model_name='covidscreeninstance',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescreen.covidscreendetails'),
        ),
    ]
