# Generated by Django 3.1.2 on 2020-11-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0005_auto_20201123_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreenquestionset'),
        ),
    ]
