# Generated by Django 3.1.2 on 2020-12-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0007_auto_20201123_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('response', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='custom_questions',
        ),
        migrations.RemoveField(
            model_name='covidscreendata',
            name='custom_responses',
        ),
        migrations.AlterField(
            model_name='response',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreendata'),
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
        migrations.AddField(
            model_name='customquestion',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescreen.event'),
        ),
        migrations.AddField(
            model_name='covidscreendata',
            name='custom_responses',
            field=models.ManyToManyField(to='prescreen.CustomQuestion'),
        ),
    ]
