# Generated by Django 3.1.2 on 2020-12-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0009_auto_20201203_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquestion',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='covid_screen_data',
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='response',
        ),
        migrations.CreateModel(
            name='CustomResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=200)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescreen.covidscreendata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescreen.customquestion')),
            ],
        ),
    ]
