# Generated by Django 3.1.2 on 2020-12-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0010_auto_20201203_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prescreen.covidscreendata'),
        ),
    ]
