# Generated by Django 3.1.2 on 2020-12-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0012_auto_20201203_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestionresponse',
            name='data',
        ),
        migrations.AddField(
            model_name='customquestionresponse',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customquestionresponse',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescreen.response'),
        ),
    ]
