# Generated by Django 3.1.2 on 2020-12-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0013_auto_20201203_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquestionresponse',
            old_name='response',
            new_name='full_response',
        ),
    ]
