# Generated by Django 3.1.2 on 2020-12-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0014_auto_20201203_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquestionresponse',
            old_name='full_response',
            new_name='response',
        ),
    ]
