# Generated by Django 3.1.2 on 2020-12-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0016_auto_20201203_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquestionresponse',
            old_name='answered_for',
            new_name='response',
        ),
    ]
