# Generated by Django 3.1.2 on 2020-12-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0017_auto_20201203_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='events',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
