# Generated by Django 3.1.2 on 2020-12-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0019_auto_20201210_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='account',
        ),
    ]
