# Generated by Django 3.1.2 on 2020-12-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('prescreen', '0020_remove_response_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
